baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Example Project Documentation Site'

[params]

 # Theme settings section
 # Theme color
 # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
custom_font_color = ""
custom_background_color = ""

# Documentation Menu section
# Menu style settings
menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

# Date format
dateformat = "" # default "2 Jan 2006"
# See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

# path name excluded from documentation menu
menu_exclusion = [
    "archives",
    "archive",
    "blog",
    "entry",
    "post",
    "posts",
]

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
        identifier = 'home'
          
# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false
   

[module]
[[module.imports]]
path = 'hugo-theme-techdoc'

   
  

